from model.senator import Senator
from model.chapa import Chapa
from model.comissao import Comissao
from model.missoes import Missoes
from model.missao import Missao
from model.academico import Academico
from model.profissao import Profissao
from model.mandato import Mandato
from model.proposicoes import Proposicoes
from model.resumo import Resumo
from model.materia import Materia
from model.pronunciamento import Pronunciamento
